name: Run Localnet

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start-localnet:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      - name: Start Localnet
        run: yarn hardhat localnet --stop-after-init
